export const userTypes = {
	USER_FETCH_ASYNC: 'USER_FETCH_ASYNC',
	USER_FETCH_REQUESTED: 'USER_FETCH_REQUESTED',
	USER_FETCH_SUCCEDED: 'USER_FETCH_SUCCEDED',
	USER_FETCH_FAILED: 'USER_FETCH_FAILED',
};
